---
version: "3"

services:
  dev-terra:
    image: dev-terra:latest
    container_name: dev-terra
    user: "${DOCKER_UID}:${DOCKER_GID}"
    volumes:
      - ".:/home/coder/workspace:delegated"
      - "${HOME}/.io4/terra/dev/home:/home/coder"
    environment:
      PG_HOST: "terra:5432"
      PG_USER: "root"
      PG_PASSWORD: "OdWLqIhVm9a1mkwF"
    networks:
      - terra

  db:
    image: postgres:14.2-bullseye
    container_name: dev-terra-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "OdWLqIhVm9a1mkwF"
    volumes:
      - "${HOME}/.io4/terra/dev/pg-data:/var/lib/postgresql/data"
    expose:
      - 5432
    networks:
      - terra

networks:
  terra:
